[app]
name = "zener"
port = 1316
trig = 3
timeout = 60000
optlinger = false

[log]
level = "DEBUG"
dir = "logs"
name = "test.log"

[mysql]
host = "127.0.0.1"
port = 3306
user = "root"
password = "root"
database = "zener_test"

[redis]
host = "127.0.0.1"
port = 6379
password = "donotpanic"
db = 0
