[app]
port = 1316
trig = 3
timeout = 60000
optlinger = false

[log]
level = "DEBUG"
dir = "logs"

[mysql]
host = "127.0.0.1"
port = 3306
user = "root"
password = "root"
database = "zener_test"
poolSize = 12           # 数据库连接池的容量

[redis]
host = "127.0.0.1"
port = 6379
password = "root"
db = 0

[thread]
poolSize = 6 # 线程池的并行数
