services:
  # consul:
  #   image: "consul:1.15.4"
  #   ports:
  #     - "8500:8500"

  mysql:
    image: "mysql:latest"
    container_name: mysql01 # 容器名称
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zener_test
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d
    restart: always

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
