[app]
name = "Zener"

[log]
log_level = "DEBUG"
log_path = "logs"

[mysql]
host = "127.0.0.1"
port = 3306
user = "root"
password = "donotpanic"
database = "zener_test"

[redis]
host = "127.0.0.1"
port = 6379
password = "donotpanic"
db = 0
