[app]
name = "zener"

[log]
level = "DEBUG"
path = "logs"
name = "logs/test.log"

[mysql]
host = "127.0.0.1"
port = 3306
user = "root"
password = "root"
database = "zener_test"

[redis]
host = "127.0.0.1"
port = 6379
password = "donotpanic"
db = 0
